[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
solc = "0.8.17"
test = 'test/foundry'
cache_path = 'forge-cache'
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config