name: "CI"

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "npm install --hardhat"

      - name: "Lint the code"
        run: "npm run prettier"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "npm run typechain"

#     For some reason, compiled for coverage contracts producing an error:
#      Error: Transaction reverted: trying to deploy a contract whose code is too large
#     So disabling coverage until a fix would be found
#      - name: "Test the contracts and generate the coverage report"
#        run: "npm run coverage"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
