name: "CI"

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          node-version: "lts/*"

      - name: "Install the dependencies"
        run: "yarn add typescript hardhat prettier typechain"

      - name: "Check prettier"
        run: "yarn run prettier:check"

      - name: "Check for presence of .only in tests"
        run: yarn check_dot_only

      - name: "Compile the contracts and generate the TypeChain bindings"
        run: "yarn typechain"

      - name: "Check types"
        run: "yarn tsc --noEmit"

      - name: "Lint code"
        run: "yarn lint"

#     For some reason, compiled for coverage contracts producing an error:
#      Error: Transaction reverted: trying to deploy a contract whose code is too large
#     So disabling coverage until a fix would be found
#      - name: "Test the contracts and generate the coverage report"
#        run: "yarn coverage"

      - name: "tests"
        run: "yarn test"
